In [1]:
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
import warnings
warnings.filterwarnings('ignore')

In [2]:
filename = r'..\data\results\OPM_results\game_dataset.csv'
df = pd.read_csv(filename)
df.rename(columns={'mode': 'condition'}, inplace=True)

In [3]:
filename = r'..\data\results\OPM_results\game_metrics_per_n_game.csv'
df = pd.read_csv(filename)
df.loc[df.condition == 'im', 'condition'] = "IM"
df.loc[df.condition == 'qm', 'condition'] = "QM"

In [4]:
df

,total_score,game_duration,p_green_bands,aver_time,green_steps_min,band_gain_min,n_stars,points_per_star,n_hh_average,n_overkill_average,condition,n_game,subject
0,1074,3.40,68.42,12.6,31.43,14.29,10,107.40,0.30,1.5,IM,1,test1
1,2324,7.18,92.86,28.9,15.57,11.00,10,232.40,2.40,1.2,QM,1,test1
2,1183,2.57,90.91,15.5,26.45,18.71,6,197.17,0.83,0.6,QM,2,test1

In [5]:
filename = r'..\data\results\OPM_results\game_metrics_im_tests.csv'
df = pd.read_csv(filename)
df.loc[df.condition == 'im', 'condition'] = "IM"
df.loc[df.condition == 'qm', 'condition'] = "QM"

In [6]:
df

,total_score,game_duration,p_green_bands,aver_time,green_steps_min,band_gain_min,n_stars,points_per_star,n_hh_average,n_overkill_average,condition,n_game,subject
0,907,4.38,100.00,20.6,22.72,13.40,5,181.4,1.2,3.25,QM,1,test2
1,1753,3.87,81.82,12.6,32.38,23.81,10,175.3,0.5,0.10,QM,2,test2
2,1356,4.42,75.00,16.3,22.45,11.41,10,135.6,0.9,0.90,QM,3,test2

In [10]:
filename = r'..\data\results\OPM_results\game_metrics_8ch.csv'
df = pd.read_csv(filename)
df.loc[df.condition == 'im', 'condition'] = "IM"
df.loc[df.condition == 'qm', 'condition'] = "QM"

In [11]:
df

,total_score,game_duration,p_green_bands,aver_time,green_steps_min,band_gain_min,n_stars,points_per_star,n_hh_average,n_overkill_average,condition,n_game,subject
0,3716,6.58,83.33,12.05,37.34,26.64,20,185.8,0.3,0.65,QM,1,test3_8ch

In [14]:
filename = r'..\data\results\OPM_results\game_metrics_eeg_opm_tests.csv'
df = pd.read_csv(filename)
df.loc[df.condition == 'im', 'condition'] = "IM"
df.loc[df.condition == 'qm', 'condition'] = "QM"

In [15]:
df

,total_score,game_duration,p_green_bands,aver_time,green_steps_min,band_gain_min,n_stars,points_per_star,n_hh_average,n_overkill_average,condition,n_game,subject,filename
0,3092,9.22,96.67,26.20,19.24,13.89,15,206.13,1.27,2.07,eeg,1,test4_eeg_opm,['eeg_log_game_1']
1,674,2.50,64.29,14.00,23.27,6.12,7,96.29,0.57,0.83,eeg,2,test4_eeg_opm,['eeg_log_game_80']
2,-590,1.03,16.67,9.75,10.77,-38.46,4,-147.50,0.00,1.00,eeg,3,test4_eeg_opm,['eeg_log_game_95']
3,630,2.68,94.44,39.33,12.20,9.15,3,210.00,1.00,1.33,opm,1,test4_eeg_opm,['opm_log_game_1']
4,4832,8.63,98.33,17.00,30.53,26.47,20,241.60,0.90,0.80,opm,2,test4_eeg_opm,['opm_log_game_2']